version: '3.9'

services:
  mongo:
    image : mongo
    container_name: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - .\docker\mongodb\Data:/data/db
    ports:
      - "27018:27017"
    networks:
      - movieStarz

  eureka-registry:
    container_name: eureka-registry
    build:
      context: ./EurekaRegistry
    ports:
      - 8888:8080
      #- 8080
    networks:
      - movieStarz

  user-app:
    container_name: user-app
    build:
      context: ./user
    restart: always
    depends_on:
      - mongo
    ports:
      - "8082:8080"
    networks:
      - movieStarz

  review-app:
    container_name: review-app
    build:
      context: ./review
    restart: always
    depends_on:
      - mongo
    ports:
      - "8083:8080"
    networks:
      - movieStarz

  watchlist-app:
    container_name: watchlist-app
    build:
      context: ./watchlists
    restart: always
    depends_on:
      - mongo
    ports:
      - "8084:8080"
    networks:
      - movieStarz

  zuul-gateway:
    container_name: zuul-gateway
    build:
      context: ./zuul-gateway
    restart: always
    #depends_on:
      #- eureka-registry
    ports:
      - "8089:8080"
    networks:
      - movieStarz


networks:
  movieStarz:
    name: movieStarz